name: Terraform CI/CD

on:
   pull_request:
   branches:
   - main

push:
   branches:
   - main

jobs:
   terraform:
    runs-on: ubuntu-lasest

  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Terraform
    uses: hashicorp/setup-terraform@v2
    with:
        terraform_version: 1.5.0
    
  - name: Check Terraform format
    run: terraform fmt -check

  - name: Validate Terraform code
    run: terraform validate 

  - name: Terraform plan
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        run: terraform plan
